baseurl = "/"
languageCode = "en-us"
title = "Nick Pondel"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Resume"
    url = "/resume/"
[[menu.main]]
    name = "Photo Portfolio"
    url = "https://nickpondel.myportfolio.com"

[params]
    description = "Nick Pondel's Personal Site"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "logo.ico"
    
    # logo file, stored in /static/images
    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "Logo"

